# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_transfer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file_transfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ile_transfer.proto\"\x7f\n\tFileChunk\x12\x13\n\x0btransfer_id\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x11\n\tfile_size\x18\x03 \x01(\x03\x12\x12\n\nsecret_key\x18\x04 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x05 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\x0c\"\x9f\x01\n\x0eTransferStatus\x12*\n\x06status\x18\x01 \x01(\x0e\x32\x1a.TransferStatus.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0btransfer_id\x18\x03 \x01(\t\";\n\nStatusCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x12\x13\n\x0fUNAUTHENTICATED\x10\x02\x32\x42\n\x13\x46ileTransferService\x12+\n\nUploadFile\x12\n.FileChunk\x1a\x0f.TransferStatus(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILECHUNK']._serialized_start=23
  _globals['_FILECHUNK']._serialized_end=150
  _globals['_TRANSFERSTATUS']._serialized_start=153
  _globals['_TRANSFERSTATUS']._serialized_end=312
  _globals['_TRANSFERSTATUS_STATUSCODE']._serialized_start=253
  _globals['_TRANSFERSTATUS_STATUSCODE']._serialized_end=312
  _globals['_FILETRANSFERSERVICE']._serialized_start=314
  _globals['_FILETRANSFERSERVICE']._serialized_end=380
# @@protoc_insertion_point(module_scope)
